version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - ./config/prometheus-config.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    # network_mode: host

  loki:
    image: grafana/loki:2.1.0
    ports:
      - "3100:3100"
    volumes: 
      - ./config/:/etc/loki/config/
    command: -config.file=/etc/loki/config/loki-config.yaml
    # network_mode: host

  # promtail:
  #   image: grafana/promtail:2.0.0
  #   volumes:
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes: 
      - ./data/grafana:/var/lib/grafana
    # network_mode: host