server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: ctp2
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      vin: 1FUJGLDR8HLHF2069
      __path__: /var/log/CTP*